# Generated by Django 5.1.5 on 2025-01-19 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_assignment_description_en_assignment_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereview',
            name='comment_en',
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='comment_ru',
        ),
        migrations.RemoveField(
            model_name='teacherreview',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='teacherreview',
            name='text_ru',
        ),
    ]
